language: c
os: linux
dist: bionic
# before_install: 
#   - sudo apt-get install linux-headers-`uname -r`

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "KfjLwtQyYuiElVP+kuqvI1KzZn14C36on+oLjIuuVJPq0rgy/h8ENggDSSOpiW3PeizFOKPtmxmDkyAAwwY40HeV2lxYvcgcUFfapoU5g7SwSsBzrnHoybp3ANIGDHd2hA3yzNWH5Ovoqv9jAV40uEeZNSPPqpk1hrvde3hBXohvF4u9JcPD+iB2punUsHtkcsCqNkrc9or1yfqGokN2R6z/6FmOzhAqwPxJvIuIv4lo0eeJCHgFLR19fMGhLfF2dA/jZhX8PZrjlBSz0v9oxBh8vHif5M1DgjIYHwIVRyscF/WVTJ+eD5hGfaRMDXzzB66ULX/GJ/EpYXKcOSqfOTK1cFh5t0fx0nsZ+6mZ+xZwZ0On6+OyZ35ytEVIK8mqDDR0TJ2vVhlPWm0Yb/zX9QIWXVsc1Pyn6m2I2iYlw/eEzXcxTjNp78FHL/nZycrEd+HBw3g9r7ycDon0oPSAYSc75khikcKvXC2WpD9EKtj3IRQKWx+Bl/f7ujFYBmgXwZI34C5CYKE1hAmf2NotRbpbI0M19+X+KBbPdlg9ExZfv0aKyomgGME6tpvLlfrRKeFEzi2vvk6UBO9QSlAoCDle7TbnJ1WxPm/16Ym4k8nQlinaj9VT0UjSmb9Xu2Sz4RtXKzukm64hdWhhxscpNgV/h0YWgp8O2eXDnady+Lc="

before_install:
  - sudo apt-get install linux-headers-`uname -r`
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Shymaxtic/CANUSBDriver"
      description: "USB CAN Linux driver"
    notification_email: shymaxtic@gmail.com
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: coverity_scan
    
script: make
